### ISSUE TITLE
ModuleNotFoundError: No module named 'ovdet'

### ISSUE THREAD

**Issue by kinredon** [wusize/ovdet#14]
Hi, thanks for your excellent work!

I tried to generate the [Class Embeddings](https://github.com/wusize/ovdet/blob/main/configs/baron/ov_coco/README.md#class-embeddings) and run the following commands:
```
python tools/hand_craft_prompt.py --model_version ViT-B/32 --ann data/coco/annotations/instances_val2017.json \
--out_path data/metadata/coco_clip_hand_craft.npy --dataset coco
```
But there is an error:

```
Traceback (most recent call last):
  File "tools/hand_craft_prompt.py", line 7, in <module>
    import ovdet.models.vlms.clip.clip as CLIP
ModuleNotFoundError: No module named 'ovdet'
```
What is the problem with me? can you give me some help?

**Comment by wusize** [comment]
You may try adding the path of the project to the environmental variables, e.g.,
‘’’
import sys
sys.path.insert(0, 'path/to/this/project/')
‘’’

**Comment by kinredon** [comment]
Thanks for your help. I fixed this error now!
