### ISSUE TITLE
KeyError: 'OVDTwoStageDetector is not in the model registry.

### ISSUE THREAD

**Issue by qsunyuan** [wusize/ovdet#16]
非常好的工作！我看了启发很大。

我在测试baron-kd-faster-rcnn-r50-fpn-syncbn-90kx2的时候，出现了这个bug。希望作者能够提供一些建议。

KeyError: 'OVDTwoStageDetector is not in the model registry. Please check whether the value of `OVDTwoStageDetector` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

另外我注意到一个相似的问题：[KeyError: 'None is not in the dataset registry' · Issue #1324 · open-mmlab/mmdetection](https://github.com/open-mmlab/mmdetection/issues/1324)

**Comment by wusize** [comment]
May I know the directory you run the scripts as well as the commands you used?

**Comment by qsunyuan** [comment]
Thx for ur very quick replay. 

Here are some details:

Command:
```
git clone <this repo>
cd ovdet
export CUDA_VISIBLE_DEVICES=1,2
bash tools/dist_test.sh configs/baron/ov_coco/baron_kd_faster_rcnn_r50_fpn_syncbn_90kx2.py checkpoints/iter_90000.pth 2
```

Some other details:
- I firstly add the python environment according to https://github.com/wusize/ovdet/issues/14
- I comment the 'import ovdet' in https://github.com/wusize/ovdet/blob/c67eecf11db35a7cbe020298572654506cfdff3e/tools/test.py#L13 due to the another error: KeyError: 'CocoCaptionDataset is already registered in dataset at mmdet.datasets.coco_caption'

**Comment by qsunyuan** [comment]
`torch version`: 1.12.1+cu113
`mmdet version`: 3.1.0

I run this command with adding python environment `sys.path.insert()`:

```
python tools/hand_craft_prompt.py --model_version ViT-B/32 --ann data/coco/annotations/instances_val2017.json \
--out_path data/metadata/coco_clip_hand_craft.npy --dataset coco
```

KeyError: 'CocoCaptionDataset is already registered in dataset at mmdet.datasets.coco_caption'

I find that `data/metadata/coco_clip_hand_craft_attn12.npy` is already in `data/metadata`, so I directly skip it with next test command.

**Comment by qsunyuan** [comment]
I reinstall the whole libraries locally and things go well, I got the novel mAP 0.346 and base mAP 0.606. 

btw, is there an easy way to get the results of the whole mAP (i.e. AP50: 53.5 in tabel 1 of BARON paper)

**Comment by wusize** [comment]
> I reinstall the whole libraries locally and things go well, I got the novel mAP 0.346 and base mAP 0.606.
> 
> btw, is there an easy way to get the results of the whole mAP (i.e. AP50: 53.5 in tabel 1 of BARON paper)

By default, the COCO evaluator should also print the AP50 in the output table.

**Comment by wusize** [comment]
> I reinstall the whole libraries locally and things go well, I got the novel mAP 0.346 and base mAP 0.606.
> 
> btw, is there an easy way to get the results of the whole mAP (i.e. AP50: 53.5 in tabel 1 of BARON paper)

The current evaluator does not calculate the over all mAP. You can manually calculate it by ALL = (48 * BASE + 17 * NOVEL) / 65.

**Comment by eternaldolphin** [comment]
> I reinstall the whole libraries locally and things go well, I got the novel mAP 0.346 and base mAP 0.606.
> 
> btw, is there an easy way to get the results of the whole mAP (i.e. AP50: 53.5 in tabel 1 of BARON paper)

how to reinstall the whole libraries?
