### ISSUE TITLE
LVIS pipeline

### ISSUE THREAD

**Issue by qsunyuan** [wusize/ovdet#20]
Hope to get your LVIS pipeline.

**Comment by wusize** [comment]
Sorry for the late relying. I was on vocation and will be a little busy these days. Will send you the code shortly after August 16.

**Comment by ShenghaiRong** [comment]
@wusize Excellent work and awesome code! Would you also send me the d2-based code for COCO and LVIS? 
My email: rongsh@mail.ustc.edu.cn, thank you!

**Comment by parang99** [comment]
Hi, @wusize. Thank you for sharing the great work.
I'd like to run the BARON lvis code compared to DetPro in Table 2, is it possible to share?
If possible, I would appreciate it if you could send it by email. My email address is parang@korea.ac.kr . 
Thanks.

**Comment by wusize** [comment]
I will send the d2-based code together with the link to the checkpoints of the results in the paper to you all this weekend.

**Comment by wusize** [comment]
Dear all. I have invited you to the original d2-based [repo](https://github.com/wusize/raw_ovd). Please `git checkout ensemble` to get into the right branch.

**Comment by wanghao9610** [comment]
Thanks for sharing, size @wusize .

**Comment by ShenghaiRong** [comment]
Thanks for sharing the great work! 😄

**Comment by rohit901** [comment]
@wusize can you share the d2 based code with me please?

**Comment by Lukas-Ma1** [comment]
@wusize Hi, I also hope to get your lvis training and test code. The repo link you sent seems to be unavailable, could I trouble you to send the code to my email: mashiyuan8@gmail.com. Thank you so much!

**Comment by DylanMQS** [comment]
The repo link seems to be unavailable, could I trouble you to send the code to my email: [mqs_fire@outlook.com](mailto:mqs_fire@outlook.com). Thank you so much!
