### ISSUE TITLE
About "ovdet"

### ISSUE THREAD

**Issue by xiaoyi728** [wusize/ovdet#23]
When I run the tools/train.py file, I always get an error message "ModuleNotFoundError: No module named 'ovdet'", even though I have imported the module. Can you give me some suggestions on how to solve this problem?

**Comment by wusize** [comment]
Hi! Please refer to this [issue](https://github.com/wusize/ovdet/issues/14#issuecomment-1599594312).

**Comment by xiaoyi728** [comment]
Thank you for your reply, I have found a solution to the problem.
