### ISSUE TITLE
About Novel/bbox_mAP_50 of faster_rcnn_r50_fpn_syncbn_90kx2

### ISSUE THREAD

**Issue by Leo-Yuyang** [wusize/ovdet#25]
您好，感谢您在ovd领域的出彩工作！
我在使用该repo跑实验复现指标的时候遇到了一个问题：
在其他条件（GPU数量，运行环境等）均相同的情况下，使用baron_kd_faster_rcnn_r50_fpn_syncbn_90kx2这个config能训练出正常的点：
![cefc3ceabfeba6608688775b67b471a](https://github.com/wusize/ovdet/assets/53007066/90eeebc9-4b90-4b3f-9b52-d53559838dd5)
然而，当我将config换作faster_rcnn_r50_fpn_syncbn_90kx2时，按照预期，这个将分类层改为class_embedding的方法在novel类别上的指标应该为map_50=~0.25,但训练结果却是0.01到0.02：
![image](https://github.com/wusize/ovdet/assets/53007066/87f7f504-59c1-4a24-b05a-641130ccb4da)
上图是用faster_rcnn_r50_fpn_syncbn_90kx2的训练结果，看起来这个方法在base类别上表现正常，而在novel类别上基本不具有检测能力。我将这个模型的推理结果可视化过，发现在novel类别上出框数量非常少。
我在不同的服务器上重新配置了几次环境，均稳定复现了上述问题；想咨询一下作者这个config是否存在一些问题导致了结果不符合预期？

**Comment by Leo-Yuyang** [comment]
您好，我对了下config发现我上面说的这个config文件应该不是对应论文中的Aligning Individual Regions方法，因为论文中提到了Aligning Individual Regions会使用img_encoder去提特征然后做对齐，而上述config里的image_encoder是None;
![e3ff525eb54b50c08b35bd4237b37fea](https://github.com/wusize/ovdet/assets/53007066/4a551cbc-3b5d-43b1-a501-d213da8389b2)
求问作者可否提供论文中Aligning Individual Regions方法对应的config?感谢您的支持！

**Comment by wusize** [comment]
`faster_rcnn_r50_fpn_syncbn_90kx2` only train the detector on base categories. You can see there are no baron-related losses in the log. 

Please refer to this [part](https://github.com/wusize/ovdet/blob/main/ovdet/methods/baron/baron_kd.py#L258) for the individual alignment.

**Comment by Leo-Yuyang** [comment]
Thank you for your explanation!
