### ISSUE TITLE
why use two inputs branch (det and baron_kd)

### ISSUE THREAD

**Issue by qsunyuan** [wusize/ovdet#26]
Hi!

https://github.com/wusize/ovdet/blob/c67eecf11db35a7cbe020298572654506cfdff3e/ovdet/models/detectors/two_stage.py#L52

Why do we need two branches for forward propagation? It seems that one branch can calculate det-loss and baron-kd loss and reduce the amount of calculation.

**Comment by wusize** [comment]
This is to make the code base more flexible. Disentangling the det and ovd branch can make the code base suitable for any OVD methods.
