### ISSUE TITLE
About the source of  AP50 metric

### ISSUE THREAD

**Issue by xiaoyi728** [wusize/ovdet#32]
Hello, while conducting replication, I noticed that the final results only include AP50novel, AP50base, and other metrics. However, I couldn't find the AP50 values mentioned in Table 1 of the paper. Could you please clarify the source of these AP50 values? Thank you.
![图片](https://github.com/wusize/ovdet/assets/97960923/1046c4cb-1c83-469d-b2c2-8cdf708b33ba)
![图片](https://github.com/wusize/ovdet/assets/97960923/274521f2-3b4e-468f-9e44-7d526a198484)

**Comment by wusize** [comment]
Hi! I did not include the calculation of AP50 in the released code. But you can calculate it manually by `AP50 = (AP50_base*48 + AP50_novel*17) / 65`.

**Comment by xiaoyi728** [comment]
thank you for your reply
