### ISSUE TITLE
Train  on COCO with CLIP + Caption supervision

### ISSUE THREAD

**Issue by qiandl2000** [wusize/ovdet#37]
Thanks for your work, but I have a question that how can I train the model on COCO with CLIP + Caption supervision? I found the result in your paper. But I didn't find a config file to train it on github.

**Comment by wusize** [comment]
Hi! Please refer to this [issue](https://github.com/wusize/ovdet/issues/31)

**Comment by qiandl2000** [comment]
Oh, sorry to bother you, it helps, thank you! Wish you good luck on CVPR!
