### ISSUE TITLE
How can i find the CLIP supervised model checkpoint

### ISSUE THREAD

**Issue by Parsifal133** [wusize/ovdet#38]
Hi @wusize ! Thanks for your work!

I'd like to test the CLIP supervised model, but only find a log file in the google driver link https://drive.google.com/drive/folders/1JTM0uoPQZtq7lnhZxCBwjxBUca9omYR9?usp=sharing

Do i  miss anything?

**Comment by qiandl2000** [comment]
It seems that only the path file on Caption supervision was given. Maybe you can train it yourself.

**Comment by Parsifal133** [comment]
> It seems that only the path file on Caption supervision was given. Maybe you can train it yourself.

So far it seems so. But training consumes too many resources.
Thanks for your reply anyway.

**Comment by wusize** [comment]
Hi! Apologies for forgetting to upload the checkpoints. They are being uploaded now and please check the google drive 1 hour later.
