### ISSUE TITLE
Why do you use 4ConvFC head instead of the FC head in FPN?

### ISSUE THREAD

**Issue by gugite** [wusize/ovdet#5]
Thank you for your excellent work! I notice that you use the 4ConvFC head instead of the standard FC head. As far as I know, introducing 4 Conv will give some AP gains in terms of the object detector. Do you have the results with the standard FC head? Thanks.

https://github.com/wusize/ovdet/blob/cbeb3d40492b7c871e454de32039298c475f5ac1/configs/_base_/models/faster-rcnn_r50_fpn_syncbn.py#L14

**Comment by wusize** [comment]
Hi, Thanks for your interest in our work! Yes, I used 4ConvFC to obtain a stronger object detector. This was for fair comparison with previsous papers that usually adopted a strong baseline, e.g. ViLD, DetPro. However, there is also a [config file](https://github.com/wusize/ovdet/blob/c4/configs/baron/ov_coco/baron_kd_faster_rcnn_r50_c4_90k.py) using a simple c4 based detector, which yields good result on novel AP and of course much lower base AP compared to the FPN+4ConvFC based methods.

**Comment by wusize** [comment]
Yes, that's because I use 16 gpus to train it.

**Comment by wusize** [comment]
Hi, the testing and training on coco are supported now.
