### ISSUE TITLE
Questions about inference and loss

### ISSUE THREAD

**Issue by xishanhan** [wusize/ovdet#8]
Hi, thanks for sharing your great work! I have some questions about the inference and loss of BARON.
During model inference, will a region bag be formed for proposals generated by RPN? Or just use the proposals generated by rpn, each proposal corresponds to a pseudo-word?
When calculating loss, the paper says that Lbag and Lindividual are used. How are they combined? Also, does BARON train bbox regression on base categories? If trained, is the total loss calculated as Lbag + Lindividual + Lclassification + Lbox?
I'm sorry to have so many questions. Looking forward to your reply!

**Comment by xishanhan** [comment]
If bbox regression is performed in each iteration, is the regions re-sampled for each refined proposal?

**Comment by wusize** [comment]
Hi! Sorry for the late reply. The bag of regions are only applied in training, more specifically, in the knowledge distillation process. 
Each proposal corresponds to a pre-defined number of pseudo words. More details are in the paper.

For the training on base categories, there are losses for classification and regression just like a standard object detection training.

For the bag of regions, we do not update the boxes predicted by RPN.
