### ISSUE TITLE
About coco_clip_hand_craft_attn12.npy

### ISSUE THREAD

**Issue by wwiwush** [wusize/ovdet#9]
Thanks for this nice work! I'd like to know how was coco_clip_hand_craft_attn12.npy generated and the difference between 
 coco_clip_hand_craft_attn12.npy and coco_clip_hand_craft.npy. Thank you!

**Comment by wusize** [comment]
Hi, thanks for your interest! This to alleviate overfitting when training COCO. We use the output of the last (12th) attention layer for classification.  Details are [here](https://github.com/wusize/ovdet/blob/a9b33dcb461f1099081fc6d4604d126fae7f6292/ovdet/models/roi_heads/baron_bbox_heads/bbox_head.py#L82).  You can also refer to the last paragraph of S1 section in the [supplementary material](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Wu_Aligning_Bag_of_CVPR_2023_supplemental.pdf).
